/**
 * Author:  LENOVO
 * Created: Jun 17, 2023
 */


/*
TABLE_CATALOG	
TABLE_SCHEMA	
TABLE_NAME	
COLUMN_NAME	
ORDINAL_POSITION	
COLUMN_DEFAULT	
IS_NULLABLE	
DATA_TYPE	
CHARACTER_MAXIMUM_LENGTH	
CHARACTER_OCTET_LENGTH	
NUMERIC_PRECISION	
NUMERIC_SCALE	
DATETIME_PRECISION	
CHARACTER_SET_NAME	
COLLATION_NAME	
COLUMN_TYPE	
COLUMN_KEY	
EXTRA	
PRIVILEGES	
COLUMN_COMMENT	
GENERATION_EXPRESSION	
SRS_ID */

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE `TABLE_SCHEMA` = 'fo_v301_demo_sohan' AND  `TABLE_NAME` = 'cms';


SELECT COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,COLUMN_TYPE,COLUMN_KEY,EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE `TABLE_SCHEMA` = 'fo_v301_demo_sohan' AND  `TABLE_NAME` = 'cms'
order by ORDINAL_POSITION ASC;


SELECT COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,COLUMN_TYPE,EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE `TABLE_SCHEMA` = 'fo_v301_demo_sohan' AND  `TABLE_NAME` = 'cms'
order by ORDINAL_POSITION ASC;